name: arkrides

services:

  api: 
    build:
      context: ./
      target: development
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '4010:4010'
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass redis_password_dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: